@host = http://localhost:8080

### HOME
{{host}}

### USERS
{{host}}/users

###
{{host}}/users/user-bookings/2

###
POST {{host}}/users/create-dummy-user

### EVENTS
{{host}}/events

###
{{host}}/events/event-bookings

###
{{host}}/events/event-bookings/1

###
POST {{host}}/events/create-dummy-event

###
POST {{host}}/events/create-event
Content-Type: application/json

{
  "title": "Event 1",
  "description": "Event 1 description",
  "date": "2021-09-01T00:00:00.000Z"
}

### BOOKINGS
POST {{host}}/bookings/create-booking-by-user-email
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "some@email4.com",
  "eventId": 4
}
